export const USER_UPDATE = "USER_UPDATE";
export const GET_USER = "GET_USER";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS";
export const SET_CURRENT_USER_ERROR = "SET_CURRENT_USER_ERROR";

export const EDIT_USER = 'EDIT_USER'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'